package reporter

import (
	"fmt"
	"strings"
	"time"
)

func formatSlackMessage(clusterName, analysis string) map[string]interface{} {
	timestamp := time.Now().Format("Monday, January 2, 2006")

	blocks := []map[string]interface{}{
		{
			"type": "header",
			"text": map[string]interface{}{
				"type": "plain_text",
				"text": fmt.Sprintf("Weekly K8s Health Report - %s", clusterName),
			},
		},
		{
			"type": "context",
			"elements": []map[string]interface{}{
				{
					"type": "mrkdwn",
					"text": fmt.Sprintf("Report generated on %s", timestamp),
				},
			},
		},
		{
			"type": "divider",
		},
	}

	chunks := splitTextIntoChunks(analysis, 2900)
	for _, chunk := range chunks {
		blocks = append(blocks, map[string]interface{}{
			"type": "section",
			"text": map[string]interface{}{
				"type": "mrkdwn",
				"text": chunk,
			},
		})
	}

	blocks = append(blocks,
		map[string]interface{}{
			"type": "divider",
		},
		map[string]interface{}{
			"type": "context",
			"elements": []map[string]interface{}{
				{
					"type": "mrkdwn",
					"text": "_Generated by K8s Observer powered by Claude AI_",
				},
			},
		},
	)

	return map[string]interface{}{
		"blocks": blocks,
	}
}

func splitTextIntoChunks(text string, maxLength int) []string {
	if len(text) <= maxLength {
		return []string{text}
	}

	var chunks []string
	lines := strings.Split(text, "\n")
	currentChunk := ""

	for _, line := range lines {
		if len(currentChunk)+len(line)+1 > maxLength {
			if currentChunk != "" {
				chunks = append(chunks, strings.TrimSpace(currentChunk))
				currentChunk = ""
			}

			if len(line) > maxLength {
				for i := 0; i < len(line); i += maxLength {
					end := i + maxLength
					if end > len(line) {
						end = len(line)
					}
					chunks = append(chunks, line[i:end])
				}
			} else {
				currentChunk = line + "\n"
			}
		} else {
			currentChunk += line + "\n"
		}
	}

	if currentChunk != "" {
		chunks = append(chunks, strings.TrimSpace(currentChunk))
	}

	return chunks
}
